/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tariffs
         * @description Retrieve all tariffs.
         */
        get: operations["getAllTariffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tariffs/{year}/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tariffs by currency
         * @description Retrieve tariffs for a year and currency.
         */
        get: operations["getAllTariffsByCurrency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tariffs/{year}/{currency}/{letter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tariff
         * @description Retrieve a single tariff by year, currency, and letter.
         */
        get: operations["getTariff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stamps
         * @description Retrieve all stamps, optionally filtered by year.
         */
        get: operations["getAllStamps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stamps/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stamp years
         * @description Retrieve distinct release years with stamp counts, sorted descending.
         */
        get: operations["getStampYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stamp/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get stamp
         * @description Retrieve a stamp by id.
         */
        get: operations["getStampById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Returns the authenticated user's profile. Creates the profile on first call if one does not yet exist.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/first-day-covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List first day covers
         * @description Retrieve all first day covers.
         */
        get: operations["getAllFirstDayCovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/first-day-covers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get first day cover
         * @description Retrieve a first day cover by id.
         */
        get: operations["getFirstDayCoverById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List designers
         * @description Retrieve all designers.
         */
        get: operations["getAllDesigners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get designer
         * @description Retrieve a designer by id.
         */
        get: operations["getDesignerById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error response payload. */
        ErrorResponse: {
            /** @description Error message. */
            message?: string;
            /** @description Error code. */
            code?: string;
            /**
             * Format: int32
             * @description HTTP status code.
             */
            status?: number;
        };
        /** @description Postal tariff listing by year and currency. */
        TariffsDto: {
            /** @description Tariff document identifier. */
            id: string;
            /**
             * Format: int32
             * @description Tariff year.
             */
            year: number;
            /**
             * Format: date-time
             * @description Last update timestamp.
             */
            updatedAt: string;
            /** @description Tariffs mapped by currency and letter. */
            currencies: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** @description Stamp details. */
        StampDto: {
            /** @description Stamp name. */
            name: string;
            /** @description Stamp description. */
            description: string;
            /** @description Stamp metadata. */
            meta: components["schemas"]["StampMeta"];
            /** @description Release information. */
            release: components["schemas"]["StampRelease"];
            /** @description Image URLs for the stamp. */
            images: components["schemas"]["StampImages"];
            /** @description Stamp identifier. */
            stamp_id: string;
            /**
             * Format: int32
             * @description Stamp SKU.
             */
            stampSKU: number;
        };
        /** @description Image URLs for a stamp. */
        StampImages: {
            /** @description Original image URL. */
            original: string;
            /** @description Small image URL. */
            small: string;
            /** @description Pane image URL. */
            pane: string | null;
        };
        /** @description Stamp metadata values. */
        StampMeta: {
            /** @description Denomination text. */
            denomination: string;
            /** @description Series name. */
            series: string | null;
            /** @description Designer name. */
            designer: string | null;
            /** @description Perforation indicator. */
            perforation: boolean;
            /** @description Themes associated with the stamp. */
            themes: string | null;
            /** @description Europa stamp indicator. */
            europa: boolean;
            /**
             * Format: int32
             * @description Number of stamps per pane.
             */
            stampsPerPane: number | null;
        };
        /** @description Release details for a stamp. */
        StampRelease: {
            /**
             * Format: int32
             * @description Release year.
             */
            year: number;
            /** @description Release date. */
            date: string;
            /**
             * Format: int32
             * @description Print quantity.
             */
            printQuantity: number;
            /** @description Mass issue flag. */
            isMassIssue: boolean;
            /** @description Availability flag. */
            isAvailable: boolean;
        };
        /** @description Year summary with stamp count. */
        YearSummaryDto: {
            /**
             * Format: int32
             * @description Release year.
             */
            year: number;
            /**
             * Format: int64
             * @description Number of stamps released in this year.
             */
            count: number;
        };
        /** @description Authenticated user profile. */
        UserDto: {
            /**
             * @description Keycloak user UUID (sub claim).
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id?: string;
            /**
             * @description User email address.
             * @example testuser@ecollecto.dev
             */
            email?: string;
            /**
             * @description User display name.
             * @example Test User
             */
            name?: string;
        };
        /** @description First day cover details. */
        FirstDayCoverDto: {
            /** @description Name of the first day cover. */
            name: string;
            /** @description Short description. */
            description: string;
            /** @description Designer name. */
            designer: string | null;
            /** @description Release information. */
            release: components["schemas"]["FirstDayCoverRelease"];
            /** @description Image URLs for the cover. */
            images: components["schemas"]["FirstDayCoverImages"];
            /** @description Postmark identifier. */
            postmark_id: string | null;
            /** @description Envelope identifier. */
            envelope_id: string | null;
            /**
             * Format: int32
             * @description Postmark SKU.
             */
            postmarkSKU: number | null;
            /**
             * Format: int32
             * @description Envelope SKU.
             */
            envelopeSKU: number | null;
        };
        /** @description Image URLs for a first day cover. */
        FirstDayCoverImages: {
            /** @description Envelope image URL. */
            envelope: string | null;
            /** @description Postmark image URL. */
            postmark: string | null;
        };
        /** @description Release details for a first day cover. */
        FirstDayCoverRelease: {
            /**
             * Format: int32
             * @description Release year.
             */
            year: number;
            /** @description Release date. */
            date: string;
            /**
             * Format: int32
             * @description Print quantity.
             */
            printQuantity: number;
        };
        /** @description Designer metadata. */
        DesignerDto: {
            /** @description Designer name. */
            name: string;
            /** @description Designer identifier. */
            designer_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllTariffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tariffs retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TariffsDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllTariffsByCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                currency: "UAH" | "USD";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tariffs retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tariffs not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTariff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                currency: "UAH" | "USD";
                letter: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tariff retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tariff not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllStamps: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stamps retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StampDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStampYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Years retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["YearSummaryDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStampById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stamp found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StampDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stamp not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StampDto"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllFirstDayCovers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First day covers retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FirstDayCoverDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFirstDayCoverById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First day cover found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FirstDayCoverDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description First day cover not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FirstDayCoverDto"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllDesigners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Designers retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DesignerDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDesignerById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Designer found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DesignerDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Designer not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DesignerDto"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
